# Generated by Django 4.2.6 on 2023-10-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.TextField()),
                ('titulo_propiedad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('En venta', 'En venta'), ('En alquiler', 'En alquiler'), ('En alquiler temporal', 'En alquiler temporal')], default=None, max_length=50)),
                ('estado_ac', models.CharField(choices=[('En venta', 'En venta'), ('En alquiler', 'En alquiler'), ('En alquiler temporal', 'En alquiler temporal'), ('Vendido', 'Vendido'), ('Alquilado', 'Alquilado'), ('Alquilado temporalmente', 'Alquilado temporalmente'), ('Reservado', 'Reservado')], default=None, max_length=50)),
                ('moneda', models.CharField(choices=[('$ ARS', 'ars'), ('$ USD', 'usd')], default=None, max_length=50)),
                ('precio', models.IntegerField(null=True)),
                ('publicar_precio', models.BooleanField()),
                ('dormitorios', models.IntegerField(null=True)),
                ('ambientes', models.IntegerField(null=True)),
                ('baños', models.IntegerField(null=True)),
                ('toilettes', models.IntegerField(null=True)),
                ('metros_totales', models.FloatField(null=True)),
                ('metros_cubiertos', models.FloatField(null=True)),
                ('metros_descubiertos', models.FloatField(null=True)),
                ('metros_semidescubiertos', models.FloatField(null=True)),
                ('estrenar', models.BooleanField(default=False)),
                ('antiguedad', models.IntegerField(null=True)),
                ('expensas', models.FloatField(null=True)),
                ('orientacion', models.TextField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], default=None, max_length=25)),
                ('plantas', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 o mas', '5 o mas')], default=None, max_length=25)),
                ('cocheras', models.IntegerField(null=True)),
                ('etiquetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.etiquetas')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.tipos')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
        ),
    ]
