# Generated by Django 4.2.6 on 2024-01-20 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Amenities',
                'verbose_name_plural': 'Amenities',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Etiquetas',
                'verbose_name_plural': 'Etiquetas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipos de Propiedades',
                'verbose_name_plural': 'Tipos de Propiedades',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.TextField()),
                ('titulo_propiedad', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('En venta', 'En venta'), ('En alquiler', 'En alquiler'), ('En alquiler temporal', 'En alquiler temporal')], default=None, max_length=50)),
                ('estado_ac', models.CharField(choices=[('En venta', 'En venta'), ('En alquiler', 'En alquiler'), ('En alquiler temporal', 'En alquiler temporal'), ('Vendido', 'Vendido'), ('Alquilado', 'Alquilado'), ('Alquilado temporalmente', 'Alquilado temporalmente'), ('Reservado', 'Reservado')], default=None, max_length=50)),
                ('moneda', models.CharField(choices=[('ARS', 'ars'), ('USD', 'usd')], default=None, max_length=50)),
                ('precio', models.IntegerField(null=True)),
                ('publicar_precio', models.BooleanField()),
                ('dormitorios', models.IntegerField(null=True)),
                ('ambientes', models.IntegerField(null=True)),
                ('baños', models.IntegerField(null=True)),
                ('toilettes', models.IntegerField(null=True)),
                ('metros_totales', models.FloatField(null=True)),
                ('metros_cubiertos', models.FloatField(null=True)),
                ('metros_descubiertos', models.FloatField(null=True)),
                ('metros_semidescubiertos', models.FloatField(null=True)),
                ('estrenar', models.BooleanField(default=False)),
                ('antiguedad', models.IntegerField(null=True)),
                ('expensas', models.FloatField(null=True)),
                ('orientacion', models.TextField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], default=None, max_length=25)),
                ('plantas', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 o mas', '5 o mas')], default=None, max_length=25)),
                ('cocheras', models.IntegerField(null=True)),
                ('activa', models.BooleanField(default=False)),
                ('oficina', models.CharField(choices=[('Cordoba 3719', 'Cordoba 3719'), ('Av. de los Trabajadores 2439', 'Av. de los Trabajadores 2439')], default=None, max_length=50)),
                ('amenities', models.ManyToManyField(to='propiedades.amenitiespropiedad')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.etiquetas')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.tipos')),
            ],
            options={
                'verbose_name': 'Propiedades',
                'verbose_name_plural': 'Propiedades',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
        ),
    ]
