# Generated by Django 4.2.6 on 2023-10-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='amenities',
            field=models.ManyToManyField(to='propiedades.amenitiespropiedad'),
        ),
    ]
