# Generated by Django 4.2.6 on 2023-10-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propiedades', '0002_amenitiespropiedad_propiedad_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenitiespropiedad',
            options={'managed': True, 'verbose_name': 'Amenities', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='etiquetas',
            options={'managed': True, 'verbose_name': 'Etiquetas', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'managed': True, 'verbose_name': 'Propiedades', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='tipos',
            options={'managed': True, 'verbose_name': 'Tipos de Propiedades', 'verbose_name_plural': 'Tipos de Propiedades'},
        ),
        migrations.AddField(
            model_name='propiedad',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='amenitiespropiedad',
            table='',
        ),
        migrations.AlterModelTable(
            name='etiquetas',
            table='',
        ),
        migrations.AlterModelTable(
            name='propiedad',
            table='',
        ),
        migrations.AlterModelTable(
            name='tipos',
            table='',
        ),
    ]
