# Generated by Django 4.2.6 on 2024-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_antiguedad_alter_propiedad_etiquetas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
    ]
