# Generated by Django 4.2.6 on 2024-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_tipos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img'),
        ),
    ]
