# Generated by Django 4.2.6 on 2024-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_tipos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='destacar',
            field=models.BooleanField(default=False),
        ),
    ]
